order = ["Introduction"]


[[classOrder]]
collapsed = false
classes = ["PlayerSave"]

gitSourceBranch = "main"

[docusaurus]
url = "https://playersave.ambergracesoftware.com"
baseUrl = "/"
tagline = "A Library for Building Roblox User Interfaces"

[navbar]
title = ""

[navbar.logo]
alt = "PlayerSave"
src = "logo.svg"

[home]
enabled = true
includeReadme = false

[footer]
copyright = "Written by Amber Grace. Built with Moonwave and Docusaurus"