[package]
name = "ambergracesoftware/playersave"
description = "Holistic library for storing, replicating, and observing player save data"
version = "0.0.2"
authors = [ "Amber Grace" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["aftman.toml", "default.project.json"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"